<a href="https://colab.research.google.com/github/AjMing/Pattern-EGCI463/blob/main/Week7-8/MLP_gridsearch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
import pandas as pd

In [3]:
from google.colab import drive

drive.mount("/content/drive",force_remount=True)
path="/content/drive/My Drive/data/"

Mounted at /content/drive

In [4]:
data=pd.read_csv(path+'Iris.csv')

In [5]:
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
data.loc[data['Species']=='Iris-setosa', 'Species_value']=0
data.loc[data['Species']=='Iris-versicolor', 'Species_value']=1
data.loc[data['Species']=='Iris-virginica', 'Species_value']=2

In [7]:
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Species_value
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0.0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0.0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0.0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0.0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0.0
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,2.0
146,147,6.3,2.5,5.0,1.9,Iris-virginica,2.0
147,148,6.5,3.0,5.2,2.0,Iris-virginica,2.0
148,149,6.2,3.4,5.4,2.3,Iris-virginica,2.0
149,150,5.9,3.0,5.1,1.8,Iris-virginica,2.0

In [8]:
from sklearn.model_selection import train_test_split
X_train , X_test, Y_train, Y_test=train_test_split(data.iloc[:,1:5],data.iloc[:,-1],test_size=0.2)

In [9]:
ml=MLPClassifier(verbose=1,hidden_layer_sizes=(5,3),max_iter=10000,tol=0.000000001)
ml.fit(X_train,Y_train)

Streaming output truncated to the last 5000 lines.
Iteration 5001, loss = 0.49019481
Iteration 5002, loss = 0.49019209
Iteration 5003, loss = 0.49018936
Iteration 5004, loss = 0.49018665
Iteration 5005, loss = 0.49018393
Iteration 5006, loss = 0.49018121
Iteration 5007, loss = 0.49017850
Iteration 5008, loss = 0.49017579
Iteration 5009, loss = 0.49017308
Iteration 5010, loss = 0.49017037
Iteration 5011, loss = 0.49016766
Iteration 5012, loss = 0.49016496
Iteration 5013, loss = 0.49016257
Iteration 5014, loss = 0.49015975
Iteration 5015, loss = 0.49015699
Iteration 5016, loss = 0.49015437
Iteration 5017, loss = 0.49015175
Iteration 5018, loss = 0.49014912
Iteration 5019, loss = 0.49014649
Iteration 5020, loss = 0.49014385
Iteration 5021, loss = 0.49014120
Iteration 5022, loss = 0.49013856
Iteration 5023, loss = 0.49013591
Iteration 5024, loss = 0.49013326
Iteration 5025, loss = 0.49013061
Iteration 5026, loss = 0.49012795
Iteration 5027, loss = 0.49012530
Iteration 5028, loss = 0.49012264
Iteration 5029, loss = 0.49011998
Iteration 5030, loss = 0.49011732
Iteration 5031, loss = 0.49011466
Iteration 5032, loss = 0.49011201
Iteration 5033, loss = 0.49010935
Iteration 5034, loss = 0.49010669
Iteration 5035, loss = 0.49010403
Iteration 5036, loss = 0.49010138
Iteration 5037, loss = 0.49009872
Iteration 5038, loss = 0.49009631
Iteration 5039, loss = 0.49009345
Iteration 5040, loss = 0.49009084
Iteration 5041, loss = 0.49008823
Iteration 5042, loss = 0.49008561
Iteration 5043, loss = 0.49008299
Iteration 5044, loss = 0.49008037
Iteration 5045, loss = 0.49007774
Iteration 5046, loss = 0.49007512
Iteration 5047, loss = 0.49007249
Iteration 5048, loss = 0.49006992
Iteration 5049, loss = 0.49006728
Iteration 5050, loss = 0.49006469
Iteration 5051, loss = 0.49006210
Iteration 5052, loss = 0.49005951
Iteration 5053, loss = 0.49005691
Iteration 5054, loss = 0.49005431
Iteration 5055, loss = 0.49005171
Iteration 5056, loss = 0.49004910
Iteration 5057, loss = 0.49004649
Iteration 5058, loss = 0.49004389
Iteration 5059, loss = 0.49004128
Iteration 5060, loss = 0.49003867
Iteration 5061, loss = 0.49003606
Iteration 5062, loss = 0.49003345
Iteration 5063, loss = 0.49003084
Iteration 5064, loss = 0.49002828
Iteration 5065, loss = 0.49002566
Iteration 5066, loss = 0.49002309
Iteration 5067, loss = 0.49002052
Iteration 5068, loss = 0.49001794
Iteration 5069, loss = 0.49001536
Iteration 5070, loss = 0.49001278
Iteration 5071, loss = 0.49001020
Iteration 5072, loss = 0.49000762
Iteration 5073, loss = 0.49000503
Iteration 5074, loss = 0.49000245
Iteration 5075, loss = 0.48999986
Iteration 5076, loss = 0.48999727
Iteration 5077, loss = 0.48999468
Iteration 5078, loss = 0.48999227
Iteration 5079, loss = 0.48998955
Iteration 5080, loss = 0.48998700
Iteration 5081, loss = 0.48998445
Iteration 5082, loss = 0.48998190
Iteration 5083, loss = 0.48997934
Iteration 5084, loss = 0.48997678
Iteration 5085, loss = 0.48997422
Iteration 5086, loss = 0.48997166
Iteration 5087, loss = 0.48996909
Iteration 5088, loss = 0.48996653
Iteration 5089, loss = 0.48996396
Iteration 5090, loss = 0.48996140
Iteration 5091, loss = 0.48995883
Iteration 5092, loss = 0.48995637
Iteration 5093, loss = 0.48995374
Iteration 5094, loss = 0.48995121
Iteration 5095, loss = 0.48994868
Iteration 5096, loss = 0.48994615
Iteration 5097, loss = 0.48994361
Iteration 5098, loss = 0.48994107
Iteration 5099, loss = 0.48993853
Iteration 5100, loss = 0.48993599
Iteration 5101, loss = 0.48993345
Iteration 5102, loss = 0.48993090
Iteration 5103, loss = 0.48992836
Iteration 5104, loss = 0.48992581
Iteration 5105, loss = 0.48992327
Iteration 5106, loss = 0.48992072
Iteration 5107, loss = 0.48991838
Iteration 5108, loss = 0.48991567
Iteration 5109, loss = 0.48991316
Iteration 5110, loss = 0.48991065
Iteration 5111, loss = 0.48990814
Iteration 5112, loss = 0.48990563
Iteration 5113, loss = 0.48990311
Iteration 5114, loss = 0.48990059
Iteration 5115, loss = 0.48989807
Iteration 5116, loss = 0.48989554
Iteration 5117, loss = 0.48989302
Iteration 5118, loss = 0.48989050
Iteration 5119, loss = 0.48988797
Iteration 5120, loss = 0.48988545
Iteration 5121, loss = 0.48988308
Iteration 5122, loss = 0.48988044
Iteration 5123, loss = 0.48987796
Iteration 5124, loss = 0.48987547
Iteration 5125, loss = 0.48987298
Iteration 5126, loss = 0.48987048
Iteration 5127, loss = 0.48986798
Iteration 5128, loss = 0.48986548
Iteration 5129, loss = 0.48986298
Iteration 5130, loss = 0.48986048
Iteration 5131, loss = 0.48985798
Iteration 5132, loss = 0.48985547
Iteration 5133, loss = 0.48985402
Iteration 5134, loss = 0.48985067
Iteration 5135, loss = 0.48984835
Iteration 5136, loss = 0.48984602
Iteration 5137, loss = 0.48984368
Iteration 5138, loss = 0.48984131
Iteration 5139, loss = 0.48983894
Iteration 5140, loss = 0.48983655
Iteration 5141, loss = 0.48983416
Iteration 5142, loss = 0.48983175
Iteration 5143, loss = 0.48982933
Iteration 5144, loss = 0.48982690
Iteration 5145, loss = 0.48982447
Iteration 5146, loss = 0.48982203
Iteration 5147, loss = 0.48981958
Iteration 5148, loss = 0.48981713
Iteration 5149, loss = 0.48981468
Iteration 5150, loss = 0.48981221
Iteration 5151, loss = 0.48980975
Iteration 5152, loss = 0.48980728
Iteration 5153, loss = 0.48980481
Iteration 5154, loss = 0.48980234
Iteration 5155, loss = 0.48979986
Iteration 5156, loss = 0.48979739
Iteration 5157, loss = 0.48979491
Iteration 5158, loss = 0.48979243
Iteration 5159, loss = 0.48978995
Iteration 5160, loss = 0.48978747
Iteration 5161, loss = 0.48978499
Iteration 5162, loss = 0.48978251
Iteration 5163, loss = 0.48978003
Iteration 5164, loss = 0.48977755
Iteration 5165, loss = 0.48977508
Iteration 5166, loss = 0.48977260
Iteration 5167, loss = 0.48977012
Iteration 5168, loss = 0.48976764
Iteration 5169, loss = 0.48976517
Iteration 5170, loss = 0.48976269
Iteration 5171, loss = 0.48976022
Iteration 5172, loss = 0.48975775
Iteration 5173, loss = 0.48975528
Iteration 5174, loss = 0.48975281
Iteration 5175, loss = 0.48975034
Iteration 5176, loss = 0.48974787
Iteration 5177, loss = 0.48974541
Iteration 5178, loss = 0.48974295
Iteration 5179, loss = 0.48974048
Iteration 5180, loss = 0.48973802
Iteration 5181, loss = 0.48973556
Iteration 5182, loss = 0.48973310
Iteration 5183, loss = 0.48973065
Iteration 5184, loss = 0.48972819
Iteration 5185, loss = 0.48972574
Iteration 5186, loss = 0.48972329
Iteration 5187, loss = 0.48972084
Iteration 5188, loss = 0.48971839
Iteration 5189, loss = 0.48971594
Iteration 5190, loss = 0.48971378
Iteration 5191, loss = 0.48971120
Iteration 5192, loss = 0.48970874
Iteration 5193, loss = 0.48970637
Iteration 5194, loss = 0.48970400
Iteration 5195, loss = 0.48970163
Iteration 5196, loss = 0.48969924
Iteration 5197, loss = 0.48969686
Iteration 5198, loss = 0.48969447
Iteration 5199, loss = 0.48969208
Iteration 5200, loss = 0.48968968
Iteration 5201, loss = 0.48968728
Iteration 5202, loss = 0.48968488
Iteration 5203, loss = 0.48968248
Iteration 5204, loss = 0.48968008
Iteration 5205, loss = 0.48967767
Iteration 5206, loss = 0.48967527
Iteration 5207, loss = 0.48967286
Iteration 5208, loss = 0.48967046
Iteration 5209, loss = 0.48966805
Iteration 5210, loss = 0.48966565
Iteration 5211, loss = 0.48966324
Iteration 5212, loss = 0.48966084
Iteration 5213, loss = 0.48965843
Iteration 5214, loss = 0.48965603
Iteration 5215, loss = 0.48965363
Iteration 5216, loss = 0.48965132
Iteration 5217, loss = 0.48964887
Iteration 5218, loss = 0.48964650
Iteration 5219, loss = 0.48964414
Iteration 5220, loss = 0.48964177
Iteration 5221, loss = 0.48963940
Iteration 5222, loss = 0.48963703
Iteration 5223, loss = 0.48963465
Iteration 5224, loss = 0.48963228
Iteration 5225, loss = 0.48962990
Iteration 5226, loss = 0.48962753
Iteration 5227, loss = 0.48962515
Iteration 5228, loss = 0.48962295
Iteration 5229, loss = 0.48962044
Iteration 5230, loss = 0.48961810
Iteration 5231, loss = 0.48961576
Iteration 5232, loss = 0.48961341
Iteration 5233, loss = 0.48961106
Iteration 5234, loss = 0.48960871
Iteration 5235, loss = 0.48960636
Iteration 5236, loss = 0.48960401
Iteration 5237, loss = 0.48960165
Iteration 5238, loss = 0.48959929
Iteration 5239, loss = 0.48959693
Iteration 5240, loss = 0.48959458
Iteration 5241, loss = 0.48959222
Iteration 5242, loss = 0.48958986
Iteration 5243, loss = 0.48958753
Iteration 5244, loss = 0.48958518
Iteration 5245, loss = 0.48958286
Iteration 5246, loss = 0.48958054
Iteration 5247, loss = 0.48957821
Iteration 5248, loss = 0.48957588
Iteration 5249, loss = 0.48957355
Iteration 5250, loss = 0.48957121
Iteration 5251, loss = 0.48956888
Iteration 5252, loss = 0.48956654
Iteration 5253, loss = 0.48956420
Iteration 5254, loss = 0.48956186
Iteration 5255, loss = 0.48955952
Iteration 5256, loss = 0.48955718
Iteration 5257, loss = 0.48955484
Iteration 5258, loss = 0.48955258
Iteration 5259, loss = 0.48955021
Iteration 5260, loss = 0.48954790
Iteration 5261, loss = 0.48954560
Iteration 5262, loss = 0.48954329
Iteration 5263, loss = 0.48954098
Iteration 5264, loss = 0.48953867
Iteration 5265, loss = 0.48953635
Iteration 5266, loss = 0.48953404
Iteration 5267, loss = 0.48953172
Iteration 5268, loss = 0.48952940
Iteration 5269, loss = 0.48952708
Iteration 5270, loss = 0.48952476
Iteration 5271, loss = 0.48952244
Iteration 5272, loss = 0.48952012
Iteration 5273, loss = 0.48951793
Iteration 5274, loss = 0.48951552
Iteration 5275, loss = 0.48951324
Iteration 5276, loss = 0.48951095
Iteration 5277, loss = 0.48950866
Iteration 5278, loss = 0.48950637
Iteration 5279, loss = 0.48950408
Iteration 5280, loss = 0.48950178
Iteration 5281, loss = 0.48949949
Iteration 5282, loss = 0.48949719
Iteration 5283, loss = 0.48949489
Iteration 5284, loss = 0.48949259
Iteration 5285, loss = 0.48949029
Iteration 5286, loss = 0.48948799
Iteration 5287, loss = 0.48948569
Iteration 5288, loss = 0.48948352
Iteration 5289, loss = 0.48948113
Iteration 5290, loss = 0.48947886
Iteration 5291, loss = 0.48947660
Iteration 5292, loss = 0.48947433
Iteration 5293, loss = 0.48947206
Iteration 5294, loss = 0.48946978
Iteration 5295, loss = 0.48946751
Iteration 5296, loss = 0.48946523
Iteration 5297, loss = 0.48946295
Iteration 5298, loss = 0.48946067
Iteration 5299, loss = 0.48945839
Iteration 5300, loss = 0.48945611
Iteration 5301, loss = 0.48945383
Iteration 5302, loss = 0.48945155
Iteration 5303, loss = 0.48944936
Iteration 5304, loss = 0.48944702
Iteration 5305, loss = 0.48944478
Iteration 5306, loss = 0.48944253
Iteration 5307, loss = 0.48944028
Iteration 5308, loss = 0.48943803
Iteration 5309, loss = 0.48943577
Iteration 5310, loss = 0.48943352
Iteration 5311, loss = 0.48943126
Iteration 5312, loss = 0.48942900
Iteration 5313, loss = 0.48942674
Iteration 5314, loss = 0.48942448
Iteration 5315, loss = 0.48942221
Iteration 5316, loss = 0.48941995
Iteration 5317, loss = 0.48941769
Iteration 5318, loss = 0.48941562
Iteration 5319, loss = 0.48941341
Iteration 5320, loss = 0.48941137
Iteration 5321, loss = 0.48940931
Iteration 5322, loss = 0.48940723
Iteration 5323, loss = 0.48940515
Iteration 5324, loss = 0.48940304
Iteration 5325, loss = 0.48940092
Iteration 5326, loss = 0.48939879
Iteration 5327, loss = 0.48939665
Iteration 5328, loss = 0.48939450
Iteration 5329, loss = 0.48939233
Iteration 5330, loss = 0.48939016
Iteration 5331, loss = 0.48938797
Iteration 5332, loss = 0.48938578
Iteration 5333, loss = 0.48938359
Iteration 5334, loss = 0.48938138
Iteration 5335, loss = 0.48937917
Iteration 5336, loss = 0.48937696
Iteration 5337, loss = 0.48937474
Iteration 5338, loss = 0.48937252
Iteration 5339, loss = 0.48937030
Iteration 5340, loss = 0.48936807
Iteration 5341, loss = 0.48936584
Iteration 5342, loss = 0.48936360
Iteration 5343, loss = 0.48936137
Iteration 5344, loss = 0.48935914
Iteration 5345, loss = 0.48935690
Iteration 5346, loss = 0.48935466
Iteration 5347, loss = 0.48935242
Iteration 5348, loss = 0.48935019
Iteration 5349, loss = 0.48934795
Iteration 5350, loss = 0.48934571
Iteration 5351, loss = 0.48934347
Iteration 5352, loss = 0.48934124
Iteration 5353, loss = 0.48933900
Iteration 5354, loss = 0.48933676
Iteration 5355, loss = 0.48933453
Iteration 5356, loss = 0.48933229
Iteration 5357, loss = 0.48933006
Iteration 5358, loss = 0.48932783
Iteration 5359, loss = 0.48932560
Iteration 5360, loss = 0.48932337
Iteration 5361, loss = 0.48932114
Iteration 5362, loss = 0.48931891
Iteration 5363, loss = 0.48931668
Iteration 5364, loss = 0.48931446
Iteration 5365, loss = 0.48931223
Iteration 5366, loss = 0.48931001
Iteration 5367, loss = 0.48930779
Iteration 5368, loss = 0.48930557
Iteration 5369, loss = 0.48930335
Iteration 5370, loss = 0.48930113
Iteration 5371, loss = 0.48929892
Iteration 5372, loss = 0.48929670
Iteration 5373, loss = 0.48929449
Iteration 5374, loss = 0.48929228
Iteration 5375, loss = 0.48929007
Iteration 5376, loss = 0.48928786
Iteration 5377, loss = 0.48928565
Iteration 5378, loss = 0.48928345
Iteration 5379, loss = 0.48928124
Iteration 5380, loss = 0.48927904
Iteration 5381, loss = 0.48927684
Iteration 5382, loss = 0.48927464
Iteration 5383, loss = 0.48927244
Iteration 5384, loss = 0.48927025
Iteration 5385, loss = 0.48926805
Iteration 5386, loss = 0.48926586
Iteration 5387, loss = 0.48926367
Iteration 5388, loss = 0.48926148
Iteration 5389, loss = 0.48925965
Iteration 5390, loss = 0.48925730
Iteration 5391, loss = 0.48925503
Iteration 5392, loss = 0.48925291
Iteration 5393, loss = 0.48925079
Iteration 5394, loss = 0.48924867
Iteration 5395, loss = 0.48924654
Iteration 5396, loss = 0.48924440
Iteration 5397, loss = 0.48924226
Iteration 5398, loss = 0.48924012
Iteration 5399, loss = 0.48923798
Iteration 5400, loss = 0.48923583
Iteration 5401, loss = 0.48923369
Iteration 5402, loss = 0.48923154
Iteration 5403, loss = 0.48922939
Iteration 5404, loss = 0.48922723
Iteration 5405, loss = 0.48922508
Iteration 5406, loss = 0.48922293
Iteration 5407, loss = 0.48922078
Iteration 5408, loss = 0.48921862
Iteration 5409, loss = 0.48921647
Iteration 5410, loss = 0.48921432
Iteration 5411, loss = 0.48921216
Iteration 5412, loss = 0.48921001
Iteration 5413, loss = 0.48920786
Iteration 5414, loss = 0.48920571
Iteration 5415, loss = 0.48920356
Iteration 5416, loss = 0.48920141
Iteration 5417, loss = 0.48919957
Iteration 5418, loss = 0.48919719
Iteration 5419, loss = 0.48919507
Iteration 5420, loss = 0.48919299
Iteration 5421, loss = 0.48919091
Iteration 5422, loss = 0.48918882
Iteration 5423, loss = 0.48918673
Iteration 5424, loss = 0.48918463
Iteration 5425, loss = 0.48918252
Iteration 5426, loss = 0.48918042
Iteration 5427, loss = 0.48917831
Iteration 5428, loss = 0.48917620
Iteration 5429, loss = 0.48917409
Iteration 5430, loss = 0.48917197
Iteration 5431, loss = 0.48916986
Iteration 5432, loss = 0.48916774
Iteration 5433, loss = 0.48916562
Iteration 5434, loss = 0.48916350
Iteration 5435, loss = 0.48916138
Iteration 5436, loss = 0.48915926
Iteration 5437, loss = 0.48915714
Iteration 5438, loss = 0.48915502
Iteration 5439, loss = 0.48915290
Iteration 5440, loss = 0.48915078
Iteration 5441, loss = 0.48914867
Iteration 5442, loss = 0.48914655
Iteration 5443, loss = 0.48914443
Iteration 5444, loss = 0.48914231
Iteration 5445, loss = 0.48914020
Iteration 5446, loss = 0.48913808
Iteration 5447, loss = 0.48913608
Iteration 5448, loss = 0.48913389
Iteration 5449, loss = 0.48913181
Iteration 5450, loss = 0.48912973
Iteration 5451, loss = 0.48912765
Iteration 5452, loss = 0.48912556
Iteration 5453, loss = 0.48912348
Iteration 5454, loss = 0.48912139
Iteration 5455, loss = 0.48911930
Iteration 5456, loss = 0.48911721
Iteration 5457, loss = 0.48911512
Iteration 5458, loss = 0.48911303
Iteration 5459, loss = 0.48911100
Iteration 5460, loss = 0.48910889
Iteration 5461, loss = 0.48910683
Iteration 5462, loss = 0.48910477
Iteration 5463, loss = 0.48910271
Iteration 5464, loss = 0.48910064
Iteration 5465, loss = 0.48909858
Iteration 5466, loss = 0.48909651
Iteration 5467, loss = 0.48909443
Iteration 5468, loss = 0.48909236
Iteration 5469, loss = 0.48909029
Iteration 5470, loss = 0.48908821
Iteration 5471, loss = 0.48908614
Iteration 5472, loss = 0.48908406
Iteration 5473, loss = 0.48908199
Iteration 5474, loss = 0.48907991
Iteration 5475, loss = 0.48907784
Iteration 5476, loss = 0.48907581
Iteration 5477, loss = 0.48907373
Iteration 5478, loss = 0.48907169
Iteration 5479, loss = 0.48906964
Iteration 5480, loss = 0.48906760
Iteration 5481, loss = 0.48906555
Iteration 5482, loss = 0.48906350
Iteration 5483, loss = 0.48906145
Iteration 5484, loss = 0.48905939
Iteration 5485, loss = 0.48905734
Iteration 5486, loss = 0.48905528
Iteration 5487, loss = 0.48905323
Iteration 5488, loss = 0.48905117
Iteration 5489, loss = 0.48904912
Iteration 5490, loss = 0.48904706
Iteration 5491, loss = 0.48904500
Iteration 5492, loss = 0.48904312
Iteration 5493, loss = 0.48904093
Iteration 5494, loss = 0.48903890
Iteration 5495, loss = 0.48903688
Iteration 5496, loss = 0.48903485
Iteration 5497, loss = 0.48903282
Iteration 5498, loss = 0.48903079
Iteration 5499, loss = 0.48902876
Iteration 5500, loss = 0.48902672
Iteration 5501, loss = 0.48902469
Iteration 5502, loss = 0.48902265
Iteration 5503, loss = 0.48902061
Iteration 5504, loss = 0.48901857
Iteration 5505, loss = 0.48901653
Iteration 5506, loss = 0.48901450
Iteration 5507, loss = 0.48901246
Iteration 5508, loss = 0.48901063
Iteration 5509, loss = 0.48900842
Iteration 5510, loss = 0.48900641
Iteration 5511, loss = 0.48900441
Iteration 5512, loss = 0.48900240
Iteration 5513, loss = 0.48900039
Iteration 5514, loss = 0.48899837
Iteration 5515, loss = 0.48899636
Iteration 5516, loss = 0.48899434
Iteration 5517, loss = 0.48899232
Iteration 5518, loss = 0.48899030
Iteration 5519, loss = 0.48898828
Iteration 5520, loss = 0.48898626
Iteration 5521, loss = 0.48898424
Iteration 5522, loss = 0.48898222
Iteration 5523, loss = 0.48898020
Iteration 5524, loss = 0.48897955
Iteration 5525, loss = 0.48897639
Iteration 5526, loss = 0.48897458
Iteration 5527, loss = 0.48897276
Iteration 5528, loss = 0.48897092
Iteration 5529, loss = 0.48896907
Iteration 5530, loss = 0.48896720
Iteration 5531, loss = 0.48896532
Iteration 5532, loss = 0.48896343
Iteration 5533, loss = 0.48896153
Iteration 5534, loss = 0.48895961
Iteration 5535, loss = 0.48895769
Iteration 5536, loss = 0.48895575
Iteration 5537, loss = 0.48895381
Iteration 5538, loss = 0.48895186
Iteration 5539, loss = 0.48894990
Iteration 5540, loss = 0.48894794
Iteration 5541, loss = 0.48894597
Iteration 5542, loss = 0.48894400
Iteration 5543, loss = 0.48894202
Iteration 5544, loss = 0.48894004
Iteration 5545, loss = 0.48893806
Iteration 5546, loss = 0.48893607
Iteration 5547, loss = 0.48893408
Iteration 5548, loss = 0.48893209
Iteration 5549, loss = 0.48893009
Iteration 5550, loss = 0.48892810
Iteration 5551, loss = 0.48892610
Iteration 5552, loss = 0.48892410
Iteration 5553, loss = 0.48892210
Iteration 5554, loss = 0.48892010
Iteration 5555, loss = 0.48891811
Iteration 5556, loss = 0.48891611
Iteration 5557, loss = 0.48891411
Iteration 5558, loss = 0.48891211
Iteration 5559, loss = 0.48891011
Iteration 5560, loss = 0.48890811
Iteration 5561, loss = 0.48890612
Iteration 5562, loss = 0.48890412
Iteration 5563, loss = 0.48890212
Iteration 5564, loss = 0.48890013
Iteration 5565, loss = 0.48889814
Iteration 5566, loss = 0.48889614
Iteration 5567, loss = 0.48889415
Iteration 5568, loss = 0.48889216
Iteration 5569, loss = 0.48889017
Iteration 5570, loss = 0.48888818
Iteration 5571, loss = 0.48888619
Iteration 5572, loss = 0.48888421
Iteration 5573, loss = 0.48888222
Iteration 5574, loss = 0.48888024
Iteration 5575, loss = 0.48887825
Iteration 5576, loss = 0.48887627
Iteration 5577, loss = 0.48887429
Iteration 5578, loss = 0.48887231
Iteration 5579, loss = 0.48887034
Iteration 5580, loss = 0.48886836
Iteration 5581, loss = 0.48886638
Iteration 5582, loss = 0.48886441
Iteration 5583, loss = 0.48886244
Iteration 5584, loss = 0.48886047
Iteration 5585, loss = 0.48885850
Iteration 5586, loss = 0.48885653

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10000) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=(5, 3), max_iter=10000, tol=1e-09, verbose=1)

In [10]:
ml.score(X_train,Y_train)

0.6583333333333333

In [11]:
ml.score(X_test,Y_test)

0.7

In [ ]:
network=MLPClassifier(verbose=1,max_iter=1000, random_state=0)
#max_=[5,10,100]
learning_rate_init=[0.1,0.01,0.2]
hidden_layer_sizes=[(3,),(5,),(7,),(9,),(100,)]
solver=["sgd","adam"]
learning_rate=["constant", "invscaling", "adaptive"]

param_grid = dict(learning_rate=learning_rate,learning_rate_init=learning_rate_init,hidden_layer_sizes=hidden_layer_sizes,solver=solver)
grid = GridSearchCV(estimator=network, param_grid=param_grid, n_jobs=-1, cv=5)
grid_result = grid.fit(X_train,Y_train)

Iteration 1, loss = 3.10946222
Iteration 2, loss = 0.92840579
Iteration 3, loss = 1.71453479
Iteration 4, loss = 1.45348834
Iteration 5, loss = 1.06946708
Iteration 6, loss = 0.75035999
Iteration 7, loss = 0.77125218
Iteration 8, loss = 0.85938586
Iteration 9, loss = 0.85325804
Iteration 10, loss = 0.78587493
Iteration 11, loss = 0.70535920
Iteration 12, loss = 0.65849587
Iteration 13, loss = 0.63507061
Iteration 14, loss = 0.62738902
Iteration 15, loss = 0.62381741
Iteration 16, loss = 0.61693980
Iteration 17, loss = 0.60320475
Iteration 18, loss = 0.58156656
Iteration 19, loss = 0.55346130
Iteration 20, loss = 0.52266390
Iteration 21, loss = 0.49496435
Iteration 22, loss = 0.47656677
Iteration 23, loss = 0.47124949
Iteration 24, loss = 0.47681761
Iteration 25, loss = 0.48582258
Iteration 26, loss = 0.48838877
Iteration 27, loss = 0.47825311
Iteration 28, loss = 0.45872330
Iteration 29, loss = 0.43866327
Iteration 30, loss = 0.42573002
Iteration 31, loss = 0.42218564
Iteration 32, loss = 0.42410234
Iteration 33, loss = 0.42425825
Iteration 34, loss = 0.41673775
Iteration 35, loss = 0.40224666
Iteration 36, loss = 0.38672260
Iteration 37, loss = 0.37737455
Iteration 38, loss = 0.37540520
Iteration 39, loss = 0.37440267
Iteration 40, loss = 0.36695377
Iteration 41, loss = 0.35291429
Iteration 42, loss = 0.33978764
Iteration 43, loss = 0.33383025
Iteration 44, loss = 0.33149292
Iteration 45, loss = 0.32387409
Iteration 46, loss = 0.30988571
Iteration 47, loss = 0.29807141
Iteration 48, loss = 0.29263203
Iteration 49, loss = 0.28653813
Iteration 50, loss = 0.27434302
Iteration 51, loss = 0.26210570
Iteration 52, loss = 0.25587081
Iteration 53, loss = 0.24919251
Iteration 54, loss = 0.23694499
Iteration 55, loss = 0.22667421
Iteration 56, loss = 0.22084214
Iteration 57, loss = 0.21194941
Iteration 58, loss = 0.20107214
Iteration 59, loss = 0.19463892
Iteration 60, loss = 0.18799010
Iteration 61, loss = 0.17818946
Iteration 62, loss = 0.17152818
Iteration 63, loss = 0.16595261
Iteration 64, loss = 0.15781707
Iteration 65, loss = 0.15183801
Iteration 66, loss = 0.14713604
Iteration 67, loss = 0.14033774
Iteration 68, loss = 0.13533978
Iteration 69, loss = 0.13124960
Iteration 70, loss = 0.12572688
Iteration 71, loss = 0.12176317
Iteration 72, loss = 0.11825551
Iteration 73, loss = 0.11377213
Iteration 74, loss = 0.11068946
Iteration 75, loss = 0.10764315
Iteration 76, loss = 0.10410470
Iteration 77, loss = 0.10170874
Iteration 78, loss = 0.09908018
Iteration 79, loss = 0.09632172
Iteration 80, loss = 0.09440427
Iteration 81, loss = 0.09216044
Iteration 82, loss = 0.09006680
Iteration 83, loss = 0.08852739
Iteration 84, loss = 0.08665817
Iteration 85, loss = 0.08507336
Iteration 86, loss = 0.08375289
Iteration 87, loss = 0.08219522
Iteration 88, loss = 0.08095832
Iteration 89, loss = 0.07979582
Iteration 90, loss = 0.07851229
Iteration 91, loss = 0.07751779
Iteration 92, loss = 0.07648698
Iteration 93, loss = 0.07544639
Iteration 94, loss = 0.07461646
Iteration 95, loss = 0.07371018
Iteration 96, loss = 0.07286866
Iteration 97, loss = 0.07215132
Iteration 98, loss = 0.07136479
Iteration 99, loss = 0.07067424
Iteration 100, loss = 0.07003345
Iteration 101, loss = 0.06935249
Iteration 102, loss = 0.06876750
Iteration 103, loss = 0.06818574
Iteration 104, loss = 0.06760085
Iteration 105, loss = 0.06709065
Iteration 106, loss = 0.06656290
Iteration 107, loss = 0.06605981
Iteration 108, loss = 0.06560241
Iteration 109, loss = 0.06512815
Iteration 110, loss = 0.06469155
Iteration 111, loss = 0.06427476
Iteration 112, loss = 0.06385179
Iteration 113, loss = 0.06346573
Iteration 114, loss = 0.06308279
Iteration 115, loss = 0.06270655
Iteration 116, loss = 0.06235780
Iteration 117, loss = 0.06200611
Iteration 118, loss = 0.06166997
Iteration 119, loss = 0.06134970
Iteration 120, loss = 0.06102830
Iteration 121, loss = 0.06072498
Iteration 122, loss = 0.06042823
Iteration 123, loss = 0.06013537
Iteration 124, loss = 0.05985793
Iteration 125, loss = 0.05958264
Iteration 126, loss = 0.05931570
Iteration 127, loss = 0.05905897
Iteration 128, loss = 0.05880397
Iteration 129, loss = 0.05855891
Iteration 130, loss = 0.05831930
Iteration 131, loss = 0.05808330
Iteration 132, loss = 0.05785610
Iteration 133, loss = 0.05763179
Iteration 134, loss = 0.05741304
Iteration 135, loss = 0.05720056
Iteration 136, loss = 0.05699064
Iteration 137, loss = 0.05678691
Iteration 138, loss = 0.05658712
Iteration 139, loss = 0.05639071
Iteration 140, loss = 0.05619974
Iteration 141, loss = 0.05601148
Iteration 142, loss = 0.05582740
Iteration 143, loss = 0.05564736
Iteration 144, loss = 0.05546996
Iteration 145, loss = 0.05529677
Iteration 146, loss = 0.05512646
Iteration 147, loss = 0.05495916
Iteration 148, loss = 0.05479543
Iteration 149, loss = 0.05463409
Iteration 150, loss = 0.05447595
Iteration 151, loss = 0.05432059
Iteration 152, loss = 0.05416764
Iteration 153, loss = 0.05401767
Iteration 154, loss = 0.05386995
Iteration 155, loss = 0.05372491
Iteration 156, loss = 0.05358239
Iteration 157, loss = 0.05344188
Iteration 158, loss = 0.05330379
Iteration 159, loss = 0.05316774
Iteration 160, loss = 0.05303383
Iteration 161, loss = 0.05290221
Iteration 162, loss = 0.05277243
Iteration 163, loss = 0.05264471
Iteration 164, loss = 0.05251885
Iteration 165, loss = 0.05239479
Iteration 166, loss = 0.05227261
Iteration 167, loss = 0.05215215
Iteration 168, loss = 0.05203350
Iteration 169, loss = 0.05191649
Iteration 170, loss = 0.05180104
Iteration 171, loss = 0.05168724
Iteration 172, loss = 0.05157502
Iteration 173, loss = 0.05146434
Iteration 174, loss = 0.05135512
Iteration 175, loss = 0.05124731
Iteration 176, loss = 0.05114093
Iteration 177, loss = 0.05103593
Iteration 178, loss = 0.05093234
Iteration 179, loss = 0.05083005
Iteration 180, loss = 0.05072901
Iteration 181, loss = 0.05062925
Iteration 182, loss = 0.05053076
Iteration 183, loss = 0.05043347
Iteration 184, loss = 0.05033738
Iteration 185, loss = 0.05024244
Iteration 186, loss = 0.05014862
Iteration 187, loss = 0.05005595
Iteration 188, loss = 0.04996436
Iteration 189, loss = 0.04987382
Iteration 190, loss = 0.04978431
Iteration 191, loss = 0.04969586
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

In [ ]:
grid_result.best_estimator_

MLPClassifier(hidden_layer_sizes=(5,), learning_rate_init=0.1, max_iter=1000,
              random_state=0, verbose=1)

In [ ]:
print(grid_result.best_params_)

{'hidden_layer_sizes': (5,), 'learning_rate': 'constant', 'learning_rate_init': 0.1, 'solver': 'adam'}

In [ ]:
grid_result.best_score_

np.float64(0.9833333333333334)

In [ ]:
grid_result.cv_results_

{'mean_fit_time': array([0.01724176, 0.27548156, 0.33834605, 0.47580419, 0.04443779,
        0.04753675, 0.03124957, 0.36813459, 0.01431379, 0.6174335 ,
        0.01338878, 0.03683228, 0.09343624, 0.35714717, 0.46187449,
        0.55747347, 0.1095798 , 0.03135085, 0.02773404, 0.1646327 ,
        0.21681795, 0.40716639, 0.02101264, 0.01860728, 0.0233654 ,
        0.15544   , 0.01316109, 0.3907023 , 0.02125754, 0.01621213,
        0.08459387, 0.14040523, 0.2484365 , 0.34209595, 0.07640686,
        0.01427474, 0.02252707, 0.10676513, 0.1979013 , 0.18128157,
        0.02715597, 0.10321231, 0.01774693, 0.10624304, 0.01325784,
        0.18245921, 0.56120992, 0.16794391, 0.27391801, 0.17272553,
        0.36916389, 0.29535069, 0.16139975, 0.1458787 , 0.30265479,
        0.23334937, 0.37193851, 0.34562426, 0.01596131, 0.26221738,
        0.44224906, 0.3020062 , 0.03511229, 0.4861577 , 0.02989645,
        0.29560485, 0.29324303, 0.16427307, 0.30845003, 0.33549523,
        0.07972221, 0.27231426, 0.03042607, 0.13528733, 0.39203625,
        0.2775063 , 0.03922167, 0.16370592, 0.02341928, 0.1840004 ,
        0.02787504, 0.2808145 , 0.53582692, 0.14772592, 0.20954442,
        0.12673721, 0.31974812, 0.16030755, 0.08859124, 0.1204577 ]),
 'std_fit_time': array([1.89154744e-03, 1.51111227e-02, 4.06984219e-02, 6.77266411e-02,
        5.44693023e-03, 8.41286192e-03, 2.59412044e-03, 8.78752554e-02,
        2.80151295e-03, 1.61681895e-01, 1.33605661e-03, 8.09911688e-03,
        2.88167298e-02, 5.26889842e-02, 4.89398276e-02, 8.25090072e-02,
        1.33967211e-02, 5.89859672e-03, 6.56615283e-03, 3.70120247e-02,
        1.48326851e-02, 4.09892518e-02, 2.38879627e-03, 6.59632780e-03,
        3.80224489e-03, 2.55306713e-02, 5.27189113e-04, 5.80228683e-02,
        6.07414569e-03, 3.96401900e-03, 1.43743555e-02, 1.54203149e-02,
        2.69685796e-02, 2.97476591e-02, 9.57963645e-03, 1.44392241e-03,
        2.45002939e-03, 1.25623588e-02, 2.65714309e-02, 1.84682161e-02,
        8.35505873e-03, 2.17001376e-02, 7.07072239e-03, 1.04507744e-02,
        2.28915242e-04, 1.00872351e-02, 7.40744416e-02, 1.94240140e-02,
        1.17909564e-01, 4.95917896e-02, 8.09185292e-02, 4.99031294e-02,
        1.07809171e-01, 2.60317328e-02, 1.14091027e-01, 6.27794404e-02,
        6.16379512e-02, 4.68234797e-02, 2.09524045e-03, 4.76546742e-02,
        5.27670198e-01, 9.13414075e-02, 5.55245664e-03, 1.94385705e-01,
        1.54809213e-02, 7.96345085e-02, 1.92611255e-02, 2.97791324e-02,
        6.86351386e-03, 4.23294045e-02, 1.65988493e-02, 3.89917493e-02,
        8.43584785e-03, 2.03324419e-02, 1.16843696e-01, 6.17804281e-02,
        8.71442679e-03, 6.34075581e-02, 6.46636194e-03, 4.97078326e-02,
        8.37637411e-04, 3.55941743e-02, 2.83794571e-02, 7.44093414e-02,
        5.39881242e-02, 1.53088613e-02, 1.25978086e-02, 1.42308550e-02,
        1.03799688e-02, 5.27266264e-02]),
 'mean_score_time': array([0.0029583 , 0.00409794, 0.00343757, 0.00651565, 0.0056747 ,
        0.0046443 , 0.00626035, 0.00541992, 0.00251656, 0.00713649,
        0.00333529, 0.00355353, 0.00559769, 0.00482545, 0.00635223,
        0.00513182, 0.00497026, 0.00425019, 0.0028419 , 0.00347285,
        0.00291176, 0.00378108, 0.00297494, 0.00443807, 0.00286751,
        0.00364165, 0.00305123, 0.00399156, 0.00294032, 0.0028358 ,
        0.00297794, 0.00367446, 0.00387402, 0.00290761, 0.00293007,
        0.00298848, 0.00281653, 0.0028985 , 0.00320311, 0.00298238,
        0.00338764, 0.00361056, 0.00493364, 0.00284271, 0.00289583,
        0.0030385 , 0.00301018, 0.0058681 , 0.003895  , 0.00670767,
        0.00507464, 0.00499625, 0.00583549, 0.00452089, 0.00548234,
        0.00546021, 0.00573611, 0.00285659, 0.00385857, 0.00461831,
        0.00392413, 0.00826292, 0.0117413 , 0.00436711, 0.00343351,
        0.00325999, 0.00475144, 0.00412917, 0.00308938, 0.00306015,
        0.00308928, 0.004217  , 0.0030159 , 0.00348678, 0.00386324,
        0.00562601, 0.0056426 , 0.00611157, 0.00506611, 0.00537686,
        0.00530782, 0.00595431, 0.00563803, 0.00314517, 0.00298119,
        0.00300179, 0.00375156, 0.0029644 , 0.00323014, 0.00267973]),
 'std_score_time': array([2.30462112e-04, 2.00267217e-03, 9.24208818e-04, 2.98860152e-03,
        1.82147071e-03, 1.53003522e-03, 1.22763208e-03, 1.99828535e-03,
        1.11798679e-04, 2.24477347e-03, 9.61001908e-04, 7.14797646e-04,
        2.45972216e-03, 1.59088190e-03, 7.83539689e-04, 2.46861481e-03,
        2.38453524e-03, 2.53764719e-03, 1.07172840e-04, 8.15671312e-04,
        1.79860132e-04, 1.22072020e-03, 2.09237014e-04, 1.88083103e-03,
        8.17879845e-05, 1.28700175e-03, 5.85047974e-04, 2.32416485e-03,
        3.64036600e-04, 1.86252887e-04, 1.20893276e-04, 1.73475125e-03,
        1.97132389e-03, 1.21330613e-04, 1.33574217e-04, 4.20240421e-04,
        7.52056404e-05, 5.20221254e-05, 5.95799918e-04, 2.34755655e-04,
        1.03735221e-03, 1.59465702e-03, 2.18799358e-03, 8.19575301e-05,
        2.77107628e-05, 1.50334483e-04, 1.88459992e-04, 1.29650719e-03,
        1.57099209e-03, 2.39563509e-03, 2.21670687e-03, 1.94183321e-03,
        2.43254744e-03, 7.60282390e-04, 2.34374085e-03, 2.18057131e-03,
        1.41194849e-03, 1.77622424e-04, 1.87524588e-03, 2.23500748e-03,
        1.87914000e-03, 5.93363447e-03, 4.35272716e-03, 2.08829750e-03,
        1.21866697e-03, 3.04244924e-04, 2.74348578e-03, 1.42565474e-03,
        4.56036234e-04, 4.22647229e-04, 3.20142538e-04, 1.81322986e-03,
        2.89247416e-04, 9.76699181e-04, 1.28355673e-03, 3.16660213e-03,
        9.80205273e-04, 2.77144693e-03, 1.44755645e-03, 1.63240351e-03,
        8.39027827e-04, 1.55808818e-03, 3.27802940e-03, 3.08631295e-04,
        3.95519105e-05, 1.21163712e-04, 1.64180150e-03, 4.77119839e-05,
        3.76233142e-04, 3.92970832e-04]),
 'param_hidden_layer_sizes': masked_array(data=[(3,), (3,), (3,), (3,), (3,), (3,), (3,), (3,), (3,),
                    (3,), (3,), (3,), (3,), (3,), (3,), (3,), (3,), (3,),
                    (5,), (5,), (5,), (5,), (5,), (5,), (5,), (5,), (5,),
                    (5,), (5,), (5,), (5,), (5,), (5,), (5,), (5,), (5,),
                    (7,), (7,), (7,), (7,), (7,), (7,), (7,), (7,), (7,),
                    (7,), (7,), (7,), (7,), (7,), (7,), (7,), (7,), (7,),
                    (9,), (9,), (9,), (9,), (9,), (9,), (9,), (9,), (9,),
                    (9,), (9,), (9,), (9,), (9,), (9,), (9,), (9,), (9,),
                    (100,), (100,), (100,), (100,), (100,), (100,), (100,),
                    (100,), (100,), (100,), (100,), (100,), (100,), (100,),
                    (100,), (100,), (100,), (100,)],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_learning_rate': masked_array(data=['constant', 'constant', 'constant', 'constant',
                    'constant', 'constant', 'invscaling', 'invscaling',
                    'invscaling', 'invscaling', 'invscaling', 'invscaling',
                    'adaptive', 'adaptive', 'adaptive', 'adaptive',
                    'adaptive', 'adaptive', 'constant', 'constant',
                    'constant', 'constant', 'constant', 'constant',
                    'invscaling', 'invscaling', 'invscaling', 'invscaling',
                    'invscaling', 'invscaling', 'adaptive', 'adaptive',
                    'adaptive', 'adaptive', 'adaptive', 'adaptive',
                    'constant', 'constant', 'constant', 'constant',
                    'constant', 'constant', 'invscaling', 'invscaling',
                    'invscaling', 'invscaling', 'invscaling', 'invscaling',
                    'adaptive', 'adaptive', 'adaptive', 'adaptive',
                    'adaptive', 'adaptive', 'constant', 'constant',
                    'constant', 'constant', 'constant', 'constant',
                    'invscaling', 'invscaling', 'invscaling', 'invscaling',
                    'invscaling', 'invscaling', 'adaptive', 'adaptive',
                    'adaptive', 'adaptive', 'adaptive', 'adaptive',
                    'constant', 'constant', 'constant', 'constant',
                    'constant', 'constant', 'invscaling', 'invscaling',
                    'invscaling', 'invscaling', 'invscaling', 'invscaling',
                    'adaptive', 'adaptive', 'adaptive', 'adaptive',
                    'adaptive', 'adaptive'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_learning_rate_init': masked_array(data=[0.1, 0.1, 0.01, 0.01, 0.2, 0.2, 0.1, 0.1, 0.01, 0.01,
                    0.2, 0.2, 0.1, 0.1, 0.01, 0.01, 0.2, 0.2, 0.1, 0.1,
                    0.01, 0.01, 0.2, 0.2, 0.1, 0.1, 0.01, 0.01, 0.2, 0.2,
                    0.1, 0.1, 0.01, 0.01, 0.2, 0.2, 0.1, 0.1, 0.01, 0.01,
                    0.2, 0.2, 0.1, 0.1, 0.01, 0.01, 0.2, 0.2, 0.1, 0.1,
                    0.01, 0.01, 0.2, 0.2, 0.1, 0.1, 0.01, 0.01, 0.2, 0.2,
                    0.1, 0.1, 0.01, 0.01, 0.2, 0.2, 0.1, 0.1, 0.01, 0.01,
                    0.2, 0.2, 0.1, 0.1, 0.01, 0.01, 0.2, 0.2, 0.1, 0.1,
                    0.01, 0.01, 0.2, 0.2, 0.1, 0.1, 0.01, 0.01, 0.2, 0.2],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=1e+20),
 'param_solver': masked_array(data=['sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam', 'sgd',
                    'adam', 'sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam',
                    'sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam', 'sgd',
                    'adam', 'sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam',
                    'sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam', 'sgd',
                    'adam', 'sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam',
                    'sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam', 'sgd',
                    'adam', 'sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam',
                    'sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam', 'sgd',
                    'adam', 'sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam',
                    'sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam', 'sgd',
                    'adam', 'sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam',
                    'sgd', 'adam', 'sgd', 'adam', 'sgd', 'adam'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'hidden_layer_sizes': (3,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.1,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.1,
   'solver': 'adam'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.01,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.01,
   'solver': 'adam'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.2,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.2,
   'solver': 'adam'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.1,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.1,
   'solver': 'adam'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.01,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.01,
   'solver': 'adam'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.2,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.2,
   'solver': 'adam'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.1,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.1,
   'solver': 'adam'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.01,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.01,
   'solver': 'adam'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.2,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (3,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.2,
   'solver': 'adam'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.1,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.1,
   'solver': 'adam'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.01,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.01,
   'solver': 'adam'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.2,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.2,
   'solver': 'adam'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.1,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.1,
   'solver': 'adam'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.01,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.01,
   'solver': 'adam'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.2,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.2,
   'solver': 'adam'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.1,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.1,
   'solver': 'adam'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.01,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.01,
   'solver': 'adam'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.2,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (5,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.2,
   'solver': 'adam'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.1,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.1,
   'solver': 'adam'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.01,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.01,
   'solver': 'adam'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.2,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.2,
   'solver': 'adam'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.1,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.1,
   'solver': 'adam'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.01,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.01,
   'solver': 'adam'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.2,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'invscaling',
   'learning_rate_init': 0.2,
   'solver': 'adam'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.1,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.1,
   'solver': 'adam'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.01,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.01,
   'solver': 'adam'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.2,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (7,),
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.2,
   'solver': 'adam'},
  {'hidden_layer_sizes': (9,),
   'learning_rate': 'constant',
   'learning_rate_init': 0.1,
   'solver': 'sgd'},
  {'hidden_layer_sizes': (9,),
   'learning_rate': 'constant',

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
learning_rate_init=[0.1,0.01,0.2]
hidden_layer_sizes=[(3,),(5,),(7,),(9,),(100,)]
solver=["sgd","adam"]
learning_rate=["constant", "invscaling", "adaptive"]
activation=["logistic","tanh","relu"]

steps = [('scaler', StandardScaler()), ('mlp', MLPClassifier(max_iter=1000,verbose=1))]
param_grid2 = dict(mlp__learning_rate_init=learning_rate_init,
                   mlp__hidden_layer_sizes=hidden_layer_sizes,
                   mlp__solver=solver,
                   mlp__learning_rate=learning_rate,
                   mlp__activation=activation)

from sklearn.pipeline import Pipeline
pipeline = Pipeline(steps)
# define the pipeline object.
grid = GridSearchCV(pipeline, param_grid=param_grid2, cv=5)

grid_result2 = grid.fit(X_train,Y_train)

In [ ]:
grid_result2.best_estimator_

Pipeline(steps=[('scaler', StandardScaler()),
                ('mlp',
                 MLPClassifier(activation='logistic', hidden_layer_sizes=(5,),
                               learning_rate='adaptive',
                               learning_rate_init=0.01, max_iter=1000,
                               solver='sgd', verbose=1))])

In [ ]:
grid_result2.best_params_

{'mlp__activation': 'logistic',
 'mlp__hidden_layer_sizes': (5,),
 'mlp__learning_rate': 'adaptive',
 'mlp__learning_rate_init': 0.01,
 'mlp__solver': 'sgd'}

In [ ]:
grid_result2.best_score_

np.float64(0.9833333333333334)